name: Main

on:
  pull_request_target:
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - ready_for_review
    - locked
    - unlocked
    - enqueued
    - dequeued
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo $JSON
        env:
          JSON: ${{ toJSON(github.event.pull_request) }}
      - run: gh pr view --json "${PR_NUMBER}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - run: sleep 10
